site_name: Django Commons
repo_url: https://github.com/django-commons/django-commons.github.io
markdown_extensions:
  - toc:
      permalink: "#"
nav:
  - Home: index.md
  - FAQ: faq.md
  - Governance: governance.md
  - Media: media.md
  - Values: values.md
